version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: canvas
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
  postgres-test:
    image: postgres:12
    environment:
      POSTGRES_USER: canvas
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: template1
    ports:
      - 5433:5432
volumes:
  postgres:
