# make this either ingress or AWS ELB kind service
---
apiVersion: apps/v1
kind: Deployment # Type of Kubernetes resource
metadata:
  name: canvas # Name of the Kubernetes resource
spec:
  replicas: 3 # Number of pods to run at any given time
  selector:
    matchLabels:
      app: canvas # This deployment applies to any Pods matching the specified label
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: canvas
    spec: # Spec for the container which will run in the Pod
      containers:
        - name: canvas
          image: karanbirsingh/canvas:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe: # To check the health of the Pod
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          # TODO: enable probe after database layer is added
          # readinessProbe: # To check if the Pod is ready to serve traffic or not
          #   httpGet:
          #     path: /readiness
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
