---
apiVersion: v1
kind: Service # Type of kubernetes resource
metadata:
  name: canvas-service # Name of the resource
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /canvas/healthz
spec:
  type: NodePort # A port is opened on each node in your cluster via Kube proxy.
  ports: # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - port: 80
      targetPort: 80 #application port
  selector:
    app: canvas
