name: Publish Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: make docker-build

      - name: Push docker image
        run: make docker-push

      # only release :latest if branch is main
      - name: Release docker image (aka latest)
        run: make docker-release
        if: endsWith(github.ref, 'main') == true
